#!/bin/bash


for rpi in rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18 

do
        ping -c 1 -w 1 -q $rpi &</dev/null
        if [ $? -eq 0 ] ;
then
        echo "$rpi: alive"
else
        echo "$rpi: dead"
fi
done

exit 0

